image: docker:stable

services:
  - docker:dind

stages:
  - build
  - push
  - deploy

variables:
  PYTHON_VERSION: "3.9"

before_script:
  - echo -n $CI_JOB_TOKEN | docker login -u gitlab-ci-token --password-stdin $CI_REGISTRY
  - export DOCKER_IMAGE="$CI_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME"

build:
  stage: build
  except:
  - tags
  script:
  - docker build
    -t $DOCKER_IMAGE:$CI_COMMIT_SHA
    --build-arg PYTHON_VERSION=$PYTHON_VERSION
    .
  - docker push $DOCKER_IMAGE:$CI_COMMIT_SHA

push master:
  stage: push
  only:
  - master
  script:
  - docker pull $DOCKER_IMAGE:$CI_COMMIT_SHA
  - docker tag $DOCKER_IMAGE:$CI_COMMIT_SHA $DOCKER_IMAGE:latest
  - docker push $DOCKER_IMAGE:latest

push tags:
  stage: push
  only:
  - tags
  script:
  - docker pull $DOCKER_IMAGE:$CI_COMMIT_SHA
  - docker tag $DOCKER_IMAGE:$CI_COMMIT_SHA $DOCKER_IMAGE:$CI_COMMIT_REF_NAME
  - docker push $DOCKER_IMAGE:$CI_COMMIT_REF_NAME

trigger-preview-deploy:
  stage: deploy
  only:
  - master
  variables:
    ANSIBLE_JOB: deploy-testing-platform-preview
  trigger:
    project: sysadmin/cfgmgt/ansible
    branch: master

trigger-production-deploy:
  stage: deploy
  only:
  - tags
  variables:
    ANSIBLE_JOB: deploy-testing-platform-production
    TESTING_PLATFORM_VERSION: "${CI_COMMIT_REF_NAME}"
  trigger:
    project: sysadmin/cfgmgt/ansible
    branch: master
