[tool.poetry]
name = "testing-platform"
version = "0.1.0"
description = ""
authors = ["Romain Kieffer"]
license = "AGPL-3.0-or-later"
readme = "README.md"
packages = [{include = "testing_platform"}]

[tool.poetry.dependencies]
python = "^3.8"
django = "^4.0.7"
django-bootstrap-v5 = ">=1.0.5,<1.1.0"
django-widget-tweaks = ">=1.4.8,<1.5.0"
django-icons = "^22.1"
django-q = ">=1.3.9,<1.4.0"
python-decouple = ">=3.5,<4.0"
iot-inspector-client = ">=0.1.2,<0.2.0"
dj-database-url = ">=0.5.0,<0.6.0"
requests = ">=2.26.0,<2.27.0"
certifi = ">=2021.5.30,<2021.6.0"
pyjwt = ">=2.2.0,<2.3.0"
sgqlc = ">=14.1,<15.0"
croniter = ">=1.0.15,<1.1.0"
imap-tools = "^0.57.0"
xmltodict = "^0.13.0"
checkdmarc = "^4.4.5"
ipwhois = "^1.2.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
