# Generated by Django 4.2.11 on 2024-06-28 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0002_tlsscanhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dmarcrecord',
            name='domain',
            field=models.CharField(help_text='Please enter the domain name the record should be generated for', max_length=255),
        ),
    ]
