# Generated by Django 4.2.11 on 2024-07-30 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0003_alter_dmarcrecord_domain'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tested_site', models.CharField(blank=True, max_length=200, null=True)),
                ('test_ran', models.CharField(blank=True, max_length=200, null=True)),
                ('report', models.JSONField()),
            ],
        ),
    ]
