# Generated by Django 4.2.11 on 2025-05-08 17:12

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("testing", "0004_testreport"),
    ]

    operations = [
        migrations.CreateModel(
            name="CSPEndpoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "allowed_origin",
                    models.URLField(
                        help_text="The domain allowed to send reports to this endpoint.",
                        validators=[
                            django.core.validators.URLValidator(schemes=["https"])
                        ],
                    ),
                ),
                (
                    "endpoint_uuid",
                    models.CharField(
                        db_index=True, editable=False, max_length=64, unique=True
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CSPReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("report_data", models.JSONField()),
                ("user_agent", models.CharField(max_length=255, null=True)),
                ("occurred_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "endpoint",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="testing.cspendpoint",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["endpoint", "occurred_at"],
                        name="testing_csp_endpoin_f71d36_idx",
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="cspendpoint",
            index=models.Index(
                fields=["user", "allowed_origin"], name="testing_csp_user_id_16ab2a_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="cspendpoint",
            constraint=models.UniqueConstraint(
                fields=("user", "allowed_origin"), name="unique_user_origin"
            ),
        ),
    ]
