map $http_x_forwarded_proto $original_proto {
    default $scheme;
    https https;
}
server {
    listen 127.0.0.1:18080;
    server_name testing.nc3.lu;
    client_max_body_size 100m;
    location /static/ {
        alias /srv/testing-static/;
        access_log off;
        expires 7d;
    }
    location / {
        proxy_pass http://127.0.0.1:18081;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $original_proto;
        proxy_read_timeout 340s;
        proxy_connect_timeout 10s;
    }
}
