# Generated by Django 4.1.3 on 2022-12-01 07:21
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("authentication", "0003_alter_user_vat_number"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="subscriptionrequest",
            name="user",
        ),
        migrations.RemoveField(
            model_name="user",
            name="tier_level",
        ),
        migrations.AlterField(
            model_name="user",
            name="groups",
            field=models.ManyToManyField(
                blank=True,
                help_text="The groups this user belongs to. "
                "A user will get all permissions granted to each of their groups.",
                related_name="user_set",
                related_query_name="user",
                to="auth.group",
                verbose_name="groups",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Designates whether this user should be treated as active. "
                "Unselect this instead of deleting accounts.",
                verbose_name="active",
            ),
        ),
        migrations.DeleteModel(
            name="Subscription",
        ),
        migrations.DeleteModel(
            name="SubscriptionRequest",
        ),
    ]
