# Generated by Django 4.2.3 on 2023-12-05 10:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0004_removed_subscription_mechanism"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="ldih_uuid",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
