# Generated by Django 4.1.3 on 2022-12-01 07:21
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("automation", "0002_whoisautomatedtest"),
    ]

    operations = [
        migrations.AlterField(
            model_name="httpautomatedtest",
            name="frequency",
            field=models.CharField(
                choices=[("D", "Daily"), ("W", "Weekly"), ("M", "Monthly")],
                help_text="Choose frequency of tests",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="pingautomatedtest",
            name="frequency",
            field=models.CharField(
                choices=[("D", "Daily"), ("W", "Weekly"), ("M", "Monthly")],
                help_text="Choose frequency of tests",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="whoisautomatedtest",
            name="frequency",
            field=models.CharField(
                choices=[("D", "Daily"), ("W", "Weekly"), ("M", "Monthly")],
                help_text="Choose frequency of tests",
                max_length=20,
            ),
        ),
    ]
